# permissions for end users to edit honzoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: honzo-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - honzoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - honzoes/status
  verbs:
  - get
