# permissions for end users to view honzoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: honzo-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - honzoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - honzoes/status
  verbs:
  - get
